- name: Apt update
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Установка утилит
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ base_packages_list }}"
