- name: Apt update
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Установка утилит
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ base_packages_list }}"

- name: Апгрейд утилит
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    only_upgrade: true
  loop: "{{ base_packages_list }}"
